---
#-------------------------------
# General Site Settings

title: Jisun
logo:
author: Jisun Hwang
description: this is meta description
email: jisun3678@gmail.com
github: https://github.com/jisun3678
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

plugins:
  - jekyll-spaceship
  - jekyll-mathjax
  - jekyll-sitemap


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m Jisun Hwang<br> Embedded / SLAM Engineer

social:
  - { icon: "fa-brands fa-github", link: "https://github.com/jisun3678" }
  - { icon: "fa-brands fa-linkedin", link: "https://www.linkedin.com/in/jisun3678" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: In the pursuit of improving the world, <br>I am consistently and gradually making sincere progress.
blurb-btn-link: "/about"
blurb-btn-name: know more

#-------------------------------

skills-title: Skills
skills:
  - { name: Embedded Systems Development, color: "#B2A4FF", value: "95%" }
  - { name: Firmware Development, color: "#B2A4FF", value: "95%" }
  - { name: SLAM & Path Planning, color: "#B2A4FF", value: "85%" }
  - { name: RTOS & Bare Metal Programming, color: "#B2A4FF", value: "90%" }

  - { name: Docker, color: "#FFDEB4", value: "85%" }
  - { name: ROS/ROS2 Development, color: "#FFDEB4", value: "80%" }
  - { name: Sensor Integration & Testing, color: "#FFDEB4", value: "85%" }
  - { name: CI/CD Pipelines, color: "#FFDEB4", value: "85%" }

  - { name: C/C++, color: "#FFB4B4", value: "90%" }
  - { name: Python, color: "#FFB4B4", value: "85%" }
  - { name: Hardware Communication Protocols, color: "#FFB4B4", value: "90%" }
  - { name: Keil & IAR Embedded Workbench, color: "#FFB4B4", value: "85%" }
#-------------------------------
# Experience Section

experience-title: Experience
experience:
  - {
      name: Senior Researcher,
      icon: "rga.png",
      date: "Jul 2023 – Present",
      team: "Artificial Intelligence Division",
      organization: "RGA Inc., Seoul, South Korea",
    }
  - {
      name: Deputy General Manager,
      icon: "jstech.png",
      date: "Mar 2018 – Jul 2023",
      team: "R&D and Planning Team",
      organization: "JS Tech Co., Ltd., South Korea",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Autonomous Driving Planning & Control Engineer Program (600 hours),
      date: "Dec 2023 – Jun 2024",
      organization: "Programmers Education Platform",
    }
  - {
      name: LED Application & Embedded Developer Program (1,400 hours),
      date: "Feb 2017 – Dec 2017",
      organization: "Korea IT Education Center",
    }
  - {
      name: BSc in Chemical Engineering,
      date: "Mar 2007 – Feb 2012",
      organization: "Kyungpook National University",
    }




#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "fpost/js_tech/ev_charging.png"
    url: "fpost/js_tech/ev_charging/"

  - image: "fpost/js_tech/iot.png"
    url: "fpost/js_tech/iot/"

  - image: "fpost/js_tech/remote_monitoring.png"
    url: "fpost/js_tech/remote_monitoring/"

  - image: "assets/images/portfolio/item-2.png"
    url: "fpost/js_tech/smart_factory/"

  - image: "fpost/js_tech/smart_grid.png"
    url: "fpost/js_tech/smart_grid/"

  - image: "assets/images/portfolio/item-3.png"
    url: "fpost/rga/orbslam/"

  - image: "assets/images/portfolio/item-3.png"
    url: "fpost/rga/pointcloud/"

# Portfolio Page
portfolio-label:
  - { title: "RGA Inc.", type: "RGA" }
  - { title: "JS Tech", type: "JSTech" }
  - { title: "3D Mapping & SLAM", type: "PointCloud" }
  - { title: "Embedded Systems & IoT", type: "Embedded" }
  - { title: "Energy Management & Remote Monitoring", type: "Energy" }
  - { title: "Smart Factory & Communication Protocols", type: "SmartFactory" }
  - { title: "EV Charging & OCPP", type: "EVCharging" }


portfolio-items:
  - image: "fpost/js_tech/ev_charging.png"
    url: "fpost/js_tech/ev_charging/"
    portfolio-type:
      - type: "JSTech"
      - type: "Embedded"
      - type: "EVCharging"

  - image: "fpost/js_tech/iot.png"
    url: "fpost/js_tech/iot/"
    portfolio-type:
      - type: "JSTech"
      - type: "Embedded"

  - image: "fpost/js_tech/remote_monitoring.png"
    url: "fpost/js_tech/remote_monitoring/"
    portfolio-type:
      - type: "JSTech"
      - type: "Embedded"
      - type: "Energy"

  - image: "assets/images/portfolio/item-2.png"
    url: "fpost/js_tech/smart_factory/"
    portfolio-type:
      - type: "JSTech"
      - type: "Embedded"
      - type: "SmartFactory"

  - image: "fpost/js_tech/smart_grid.png"
    url: "fpost/js_tech/smart_grid/"
    portfolio-type:
      - type: "JSTech"
      - type: "Embedded"
      - type: "Energy"

  - image: "assets/images/portfolio/item-3.png"
    url: "fpost/rga/orbslam/"
    portfolio-type:
      - type: "RGA"
      - type: "PointCloud"

  - image: "assets/images/portfolio/item-3.png"
    url: "fpost/rga/pointcloud/"
    portfolio-type:
      - type: "RGA"
      - type: "PointCloud"

#-------------------------------
# Blog Section
blog-tags:
  - { title: "Model Compression", type: "model compression" }
  - { title: "Object detection", type: "object detection" }
  - { title: "Segmentation", type: "segmentation" }
  - { title: "Diffusion", type: "diffusion" }
  - { title: "GAN", type: "GAN"}
  - { title: "Autonomy-driving", type: "Autonomy-driving"}
  - { title: "Dev course", type: "dev"}
  - { title: "Coding", type: "coding"}


#-------------------------------
# Contact Section

# contact-title: Contact
contact-email: jisun3678@gmail.com
